# Generated by Django 4.2.7 on 2023-12-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootNote', models.CharField(max_length=2)),
                ('scale', models.CharField(max_length=5)),
                ('note2', models.CharField(max_length=2)),
                ('note3', models.CharField(max_length=2)),
                ('note4', models.CharField(max_length=2)),
                ('note5', models.CharField(max_length=2)),
                ('note6', models.CharField(max_length=2)),
                ('note7', models.CharField(max_length=2)),
            ],
        ),
    ]
